# Generated by Django 5.2.15 on 2026-07-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PAYMENT', 'Payment'), ('FAILED_2FA', 'Failed 2FA'), ('PAYMENT_RETRY', 'Payment Retry'), ('VALIDATION', 'Validation'), ('OTHER', 'Other')], db_index=True, max_length=20, verbose_name='Action'),
        ),
    ]
