# Generated by Django 5.2.15 on 2026-07-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, help_text='Primary key of the affected object (UUID or integer)', max_length=64, null=True, verbose_name='Target Object ID'),
        ),
    ]
