# Generated by Django 5.2.15 on 2026-07-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_auditlog_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='_account_identifier',
            field=models.TextField(blank=True, db_column='account_identifier', null=True),
        ),
    ]
