# Generated by Django 5.2.15 on 2026-07-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymentmethod__account_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PAYMENT', 'Payment'), ('SUCCESSFUL_2FA', 'Successful 2FA'), ('FAILED_2FA', 'Failed 2FA'), ('PAYMENT_RETRY', 'Payment Retry'), ('VALIDATION', 'Validation'), ('INVOICE_STATUS_CHANGE', 'Invoice Status Change'), ('OTHER', 'Other')], db_index=True, max_length=32, verbose_name='Action'),
        ),
    ]
