# Generated by Django 4.2.16 on 2026-05-10 07:14

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import logistics.models.transport_provider
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesses', '0001_initial'),
        ('gov_integration', '0001_initial'),
        ('kiini', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('full_name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='drivers/profiles/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Location Name')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_transport_modes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, help_text="E.g. ['DRONE', 'BOAT', 'TRUCK']", size=None)),
                ('route_details', models.JSONField(blank=True, default=dict, help_text='Suggested route path or waypoints if available')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('tax_paid', models.BooleanField(default=False)),
                ('jamiikazini_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Final total paid by client', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='businesses.product')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shipments', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_shipments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider_type', models.CharField(choices=[('individual', 'Dereva Binafsi'), ('company', 'Kampuni ya Usafirishaji')], default='individual', help_text='Chagua kama huu ni usafiri binafsi au kampuni.', max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Weka GPS ya eneo la kikundi chako, au andika jina la eneo kama GPS haipatikani.', null=True, srid=4326)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_letter', models.FileField(blank=True, help_text='Pakia barua ya uthibitisho wa umoja wako.', null=True, upload_to=logistics.models.transport_provider.approval_letter_upload_path)),
                ('profile_image', models.ImageField(blank=True, help_text='Pakia picha yako ya utambulisho', null=True, upload_to=logistics.models.transport_provider.profile_image_upload_path)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_providers', to='kiini.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transport Provider',
                'verbose_name_plural': 'Transport Providers',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('boda_boda', 'Boda Boda'), ('tuk_tuk', 'Tuk Tuk / Bajaji'), ('public_transport', 'Public Transport / Taxi / Suzuki'), ('canter', 'Canter'), ('fuso', 'Fuso'), ('scania', 'Scania'), ('train', 'Train'), ('ship', 'Ship'), ('air', 'Air Freight')], max_length=30, verbose_name='Vehicle Type')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Registration Number')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Model Name')),
                ('capacity_kg', models.PositiveIntegerField(blank=True, help_text='Maximum weight capacity in kilograms', null=True, verbose_name='Weight Capacity (kg)')),
                ('volume_cbm', models.FloatField(blank=True, help_text='Maximum volume capacity in cubic meters', null=True, verbose_name='Volume Capacity (m³)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/images/', verbose_name='Vehicle Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('verification_statuses', models.JSONField(default=dict, help_text='\n            Example:\n            {\n                "TRA": "verified",\n                "LATRA": "pending",\n                "POLICE": "verified",\n                "INSURANCE": "failed"\n            }\n        ', verbose_name='Verification Statuses')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('active_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_vehicles', to='logistics.driver', verbose_name='Active Driver')),
                ('drivers', models.ManyToManyField(blank=True, related_name='vehicles', to='logistics.driver', verbose_name='Assigned Drivers')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='logistics.transportprovider')),
            ],
        ),
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('requestor_type', models.CharField(choices=[('business', 'Business'), ('institution', 'Institution')], max_length=20, verbose_name='Requestor Type')),
                ('package_description', models.TextField(verbose_name='Package Description')),
                ('weight_kg', models.FloatField(verbose_name='Weight (kg)')),
                ('volume_cbm', models.FloatField(blank=True, null=True, verbose_name='Volume (m³)')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Estimated Value')),
                ('suggested_transport_type', models.CharField(choices=[('boda_boda', 'Boda Boda'), ('tuk_tuk', 'Tuk Tuk / Bajaji'), ('public_transport', 'Public Transport / Taxi / Suzuki'), ('canter', 'Canter'), ('fuso', 'Fuso'), ('scania', 'Scania'), ('train', 'Train'), ('ship', 'Ship'), ('air', 'Air Freight')], max_length=30, verbose_name='Suggested Transport Type')),
                ('pickup_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Pickup Location')),
                ('dropoff_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Dropoff Location')),
                ('pickup_address_text', models.CharField(max_length=255, verbose_name='Pickup Address Text')),
                ('dropoff_address_text', models.CharField(max_length=255, verbose_name='Dropoff Address Text')),
                ('origin_country', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_country', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Request Status')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Is Accepted')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='businesses.business', verbose_name='Business')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='kiini.institution', verbose_name='Institution')),
            ],
            options={
                'verbose_name': 'Transport Request',
                'verbose_name_plural': 'Transport Requests',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportProviderVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driving_license_verification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driving_license_verification', to='gov_integration.verificationrequest')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_verifications', to='kiini.institution')),
                ('latra_permit_verification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latra_permit_verification', to='gov_integration.verificationrequest')),
                ('nida_verification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nida_transport_verification', to='gov_integration.verificationrequest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_verification', to=settings.AUTH_USER_MODEL)),
                ('vehicle_license_verification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_license_verification', to='gov_integration.verificationrequest')),
            ],
            options={
                'verbose_name': 'Transport Provider Verification',
                'verbose_name_plural': 'Transport Providers Verifications',
            },
        ),
        migrations.CreateModel(
            name='TransportLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(help_text='Order of leg in shipment route')),
                ('origin_name', models.CharField(max_length=255)),
                ('origin_coords', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('destination_name', models.CharField(max_length=255)),
                ('destination_coords', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('mode', models.CharField(choices=[('TRUCK', 'Truck'), ('DRONE', 'Drone'), ('BOAT', 'Boat'), ('TRAIN', 'Train'), ('BIKE', 'Bike'), ('AIR', 'Airplane'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('DELAYED', 'Delayed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='SCHEDULED', max_length=20)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('last_tracked_at', models.DateTimeField(blank=True, null=True)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('distance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('jamiikazini_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total cost for this leg', max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legs', to='logistics.transportprovider')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='logistics.shipment')),
            ],
            options={
                'ordering': ['shipment', 'sequence_number'],
                'unique_together': {('shipment', 'sequence_number')},
            },
        ),
        migrations.CreateModel(
            name='TransportAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=20)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.transportprovider')),
                ('transport_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logistics.transportrequest')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='transport_providers',
            field=models.ManyToManyField(blank=True, related_name='shipments', to='logistics.transportprovider'),
        ),
        migrations.CreateModel(
            name='LegStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('DELAYED', 'Delayed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='logistics.transportleg')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='transport_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='logistics.transportprovider'),
        ),
    ]
