# Generated by Django 4.2.16 on 2026-07-14 21:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_order_delivery_fee_order_fulfillment_type_and_more'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('boda_boda', 'Boda Boda'), ('tuk_tuk', 'Tuk Tuk / Bajaji'), ('public_transport', 'Public Transport / Taxi / Suzuki'), ('canter', 'Canter'), ('fuso', 'Fuso'), ('scania', 'Scania'), ('train', 'Train'), ('ship', 'Ship'), ('air', 'Air Freight')], max_length=30, unique=True, verbose_name='Vehicle Type')),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Fare')),
                ('per_km_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate per Km')),
                ('minimum_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimum Fare')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transport Rate Card',
                'verbose_name_plural': 'Transport Rate Cards',
            },
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='agreed_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='client_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='estimated_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estimated Fare'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='order',
            field=models.OneToOneField(blank=True, help_text='Order husika ikiwa ombi hili la usafiri limetokana na ununuzi wa bidhaa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_request', to='businesses.order', verbose_name='Order'),
        ),
        migrations.CreateModel(
            name='FareProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('proposed_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.transportprovider')),
                ('transport_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_proposals', to='logistics.transportrequest')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.vehicle')),
            ],
            options={
                'verbose_name': 'Fare Proposal',
                'verbose_name_plural': 'Fare Proposals',
                'ordering': ['-created_at'],
            },
        ),
    ]
