# Generated by Django 4.2.16 on 2026-07-15 20:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_transportratecard_transportassignment_agreed_fare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportassignment',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
