# Generated by Django 4.2.16 on 2026-07-16 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0003_alter_transportassignment_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text="Mtu binafsi aliyeomba huduma hii ya usafiri moja kwa moja - bila kuhusiana na ununuzi wa bidhaa (requestor_type='individual').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_transport_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
        migrations.AlterField(
            model_name='transportratecard',
            name='vehicle_type',
            field=models.CharField(choices=[('boda_boda', 'Boda Boda'), ('bajaji', 'Bajaji'), ('suzuki_carry', 'Suzuki Carry'), ('tuk_tuk', 'Tuk Tuk (Tricycle Cargo)'), ('public_transport', 'Daladala'), ('bus', 'Bus'), ('canter', 'Canter'), ('fuso', 'Fuso'), ('scania', 'Scania'), ('train', 'Train'), ('ship', 'Ship'), ('air', 'Air Freight')], max_length=30, unique=True, verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='requestor_type',
            field=models.CharField(choices=[('business', 'Business'), ('institution', 'Institution'), ('individual', 'Individual')], max_length=20, verbose_name='Requestor Type'),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='suggested_transport_type',
            field=models.CharField(choices=[('boda_boda', 'Boda Boda'), ('bajaji', 'Bajaji'), ('suzuki_carry', 'Suzuki Carry'), ('tuk_tuk', 'Tuk Tuk (Tricycle Cargo)'), ('public_transport', 'Daladala'), ('bus', 'Bus'), ('canter', 'Canter'), ('fuso', 'Fuso'), ('scania', 'Scania'), ('train', 'Train'), ('ship', 'Ship'), ('air', 'Air Freight')], max_length=30, verbose_name='Suggested Transport Type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('boda_boda', 'Boda Boda'), ('bajaji', 'Bajaji'), ('suzuki_carry', 'Suzuki Carry'), ('tuk_tuk', 'Tuk Tuk (Tricycle Cargo)'), ('public_transport', 'Daladala'), ('bus', 'Bus'), ('canter', 'Canter'), ('fuso', 'Fuso'), ('scania', 'Scania'), ('train', 'Train'), ('ship', 'Ship'), ('air', 'Air Freight')], max_length=30, verbose_name='Vehicle Type'),
        ),
    ]
