# Generated by Django 4.2.16 on 2026-07-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_transportrequest_requested_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportproviderverification',
            name='driver_license_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
