# Generated by Django 4.2.16 on 2026-07-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_transportproviderverification_driver_license_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportratecard',
            name='per_kg_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra charge per kg of cargo weight - 0 for shared/scheduled-route vehicles (daladala, bus) where a small parcel rides along a fixed fare.', max_digits=10, verbose_name='Rate per Kg'),
        ),
        migrations.AlterField(
            model_name='transportratecard',
            name='vehicle_type',
            field=models.CharField(choices=[('bicycle', 'Bicycle'), ('boda_boda', 'Boda Boda'), ('bajaji', 'Bajaji'), ('taxi', 'Taxi'), ('suzuki_carry', 'Suzuki Carry'), ('tuk_tuk', 'Tuk Tuk (Tricycle Cargo)'), ('public_transport', 'Daladala'), ('bus', 'Bus'), ('canter', 'Canter'), ('fuso', 'Fuso'), ('scania', 'Scania'), ('train', 'Train'), ('ship', 'Ship'), ('air', 'Air Freight')], max_length=30, unique=True, verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='suggested_transport_type',
            field=models.CharField(choices=[('bicycle', 'Bicycle'), ('boda_boda', 'Boda Boda'), ('bajaji', 'Bajaji'), ('taxi', 'Taxi'), ('suzuki_carry', 'Suzuki Carry'), ('tuk_tuk', 'Tuk Tuk (Tricycle Cargo)'), ('public_transport', 'Daladala'), ('bus', 'Bus'), ('canter', 'Canter'), ('fuso', 'Fuso'), ('scania', 'Scania'), ('train', 'Train'), ('ship', 'Ship'), ('air', 'Air Freight')], max_length=30, verbose_name='Suggested Transport Type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('bicycle', 'Bicycle'), ('boda_boda', 'Boda Boda'), ('bajaji', 'Bajaji'), ('taxi', 'Taxi'), ('suzuki_carry', 'Suzuki Carry'), ('tuk_tuk', 'Tuk Tuk (Tricycle Cargo)'), ('public_transport', 'Daladala'), ('bus', 'Bus'), ('canter', 'Canter'), ('fuso', 'Fuso'), ('scania', 'Scania'), ('train', 'Train'), ('ship', 'Ship'), ('air', 'Air Freight')], max_length=30, verbose_name='Vehicle Type'),
        ),
    ]
