# Generated by Django 4.2.16 on 2026-07-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_transportratecard_per_kg_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_photo',
            field=models.ImageField(blank=True, help_text='Picha ya leseni ya udereva - inasaidia uthibitisho wa mwongozo.', null=True, upload_to='drivers/licenses/'),
        ),
        migrations.AddField(
            model_name='transportprovider',
            name='company_name',
            field=models.CharField(blank=True, help_text="Jina rasmi la kampuni - linahitajika kama provider_type ni 'company'.", max_length=255),
        ),
        migrations.AddField(
            model_name='transportprovider',
            name='company_registration_number',
            field=models.CharField(blank=True, help_text='Namba ya usajili wa kampuni (TIN au BRELA).', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='latra_permit_number',
            field=models.CharField(blank=True, help_text='Namba ya kibali cha usafirishaji kutoka LATRA (au mamlaka husika) kwa gari hili mahususi.', max_length=50, verbose_name='LATRA Permit Number'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='latra_permit_photo',
            field=models.ImageField(blank=True, help_text='Picha ya kibali cha LATRA cha gari hili.', null=True, upload_to='vehicles/latra_permits/', verbose_name='LATRA Permit Photo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_photo',
            field=models.ImageField(blank=True, help_text='Picha ya cheti/kadi ya usajili wa gari.', null=True, upload_to='vehicles/registration_cards/', verbose_name='Registration Card Photo'),
        ),
    ]
