# Generated by Django 4.2.16 on 2026-07-22 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gov_integration', '0002_verificationrequest_business'),
        ('logistics', '0007_driver_license_photo_transportprovider_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportproviderverification',
            name='latra_permit_verification',
        ),
        migrations.RemoveField(
            model_name='transportproviderverification',
            name='vehicle_license_verification',
        ),
        migrations.CreateModel(
            name='VehicleVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latra_permit_verification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latra_vehicle_verification', to='gov_integration.verificationrequest')),
                ('tra_registration_verification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tra_vehicle_verification', to='gov_integration.verificationrequest')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='logistics.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Verification',
                'verbose_name_plural': 'Vehicle Verifications',
            },
        ),
    ]
