# Generated by Django 4.2.16 on 2026-07-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_remove_transportproviderverification_latra_permit_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportprovider',
            name='country_code',
            field=models.CharField(choices=[('TZ', 'Tanzania'), ('KE', 'Kenya'), ('UG', 'Uganda'), ('RW', 'Rwanda'), ('BI', 'Burundi'), ('SS', 'South Sudan')], default='TZ', help_text='Nchi ya mtoa-huduma huyu - inaamua ni mamlaka gani (TRA/LATRA, NTSA, URSB, n.k.) inayotumika kuthibitisha NIDA yake, leseni, na magari yake.', max_length=2),
        ),
    ]
