# Generated by Django 4.2.16 on 2026-05-10 07:14

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to top up', max_digits=12)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='INITIATED', max_length=20)),
                ('channel', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('pawapay', 'PawaPay')], help_text='Payment channel or method', max_length=50)),
                ('reference', models.CharField(help_text='Unique reference for this topup request', max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, help_text='Optional metadata for channel-specific data', null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Time when top up was confirmed', null=True)),
            ],
            options={
                'verbose_name': 'Top Up',
                'verbose_name_plural': 'Top Ups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('TOP_UP', 'Top Up'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('idempotency_key', models.CharField(blank=True, help_text='Key used to enforce idempotency for this transaction', max_length=128, null=True, unique=True)),
                ('_reference', models.CharField(db_column='reference', max_length=512, unique=True)),
                ('_receipt', models.TextField(blank=True, db_column='receipt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
    ]
