# Generated by Django 4.2.16 on 2026-05-10 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jamiiwallet.models.wallet


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('jamiiwallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(default=jamiiwallet.models.wallet.get_default_currency, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='payments.currency'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='counterparty',
            field=models.ForeignKey(blank=True, help_text='Counterparty user involved in this transaction, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_counterparty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency associated with this Transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.currency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='initiated_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reversed_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_of', to='jamiiwallet.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(blank=True, help_text='Wallet associated with this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='jamiiwallet.wallet'),
        ),
        migrations.AddField(
            model_name='topup',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topup', to='jamiiwallet.transaction'),
        ),
        migrations.AddField(
            model_name='topup',
            name='user',
            field=models.ForeignKey(help_text='User requesting the top up', on_delete=django.db.models.deletion.CASCADE, related_name='topups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'transaction_type', 'status'], name='jamiiwallet_wallet__16149d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['idempotency_key'], name='jamiiwallet_idempot_57a8a6_idx'),
        ),
    ]
