# Generated by Django 4.2.16 on 2026-07-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiiwallet', '0003_transaction_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Payer mobile money phone number (for PawaPay deposits)', max_length=20),
        ),
        migrations.AddField(
            model_name='topup',
            name='provider',
            field=models.CharField(blank=True, default='', help_text='Mobile money provider / MNO code, e.g. TIGO_TZA (PawaPay)', max_length=50),
        ),
    ]
