# Generated by Django 4.2.16 on 2026-07-11 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jamiiwallet', '0004_topup_phone_topup_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to withdraw', max_digits=12)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='INITIATED', max_length=20)),
                ('channel', models.CharField(choices=[('pawapay', 'PawaPay')], default='pawapay', help_text='Payout channel or method', max_length=50)),
                ('phone', models.CharField(blank=True, default='', help_text='Recipient mobile money phone number (for PawaPay payouts)', max_length=20)),
                ('provider', models.CharField(blank=True, default='', help_text='Mobile money provider / MNO code, e.g. TIGO_TZA (PawaPay)', max_length=50)),
                ('reference', models.CharField(help_text='Unique reference for this withdrawal request', max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, help_text='Optional metadata for channel-specific data', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Time when withdrawal was completed', null=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal', to='jamiiwallet.transaction')),
                ('user', models.ForeignKey(help_text='User requesting the withdrawal', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
                'ordering': ['-created_at'],
            },
        ),
    ]
