# Generated by Django 4.2.16 on 2026-07-12 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jamiiwallet', '0005_withdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Kiasi cha kutuma', max_digits=12)),
                ('note', models.CharField(blank=True, default='', help_text='Ujumbe wa hiari kwa mpokeaji', max_length=255)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='INITIATED', max_length=20)),
                ('reference', models.CharField(help_text='Unique reference kwa uhamisho huu', max_length=64, unique=True)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(help_text='User anayepokea pesa', on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to=settings.AUTH_USER_MODEL)),
                ('recipient_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_received', to='jamiiwallet.transaction')),
                ('sender', models.ForeignKey(help_text='User anayetuma pesa', on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to=settings.AUTH_USER_MODEL)),
                ('sender_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_sent', to='jamiiwallet.transaction')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
