# Generated by Django 4.2.16 on 2026-07-12 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jamiiwallet', '0006_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('payer', models.ForeignKey(help_text='User anayeombwa alipe', on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(help_text='User anayeomba pesa', on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests_made', to=settings.AUTH_USER_MODEL)),
                ('resulting_transfer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_request', to='jamiiwallet.transfer')),
            ],
            options={
                'verbose_name': 'Payment Request',
                'verbose_name_plural': 'Payment Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
