# Generated by Django 4.2.16 on 2026-07-12 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jamiiwallet', '0007_paymentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text='Jina la kumbukumbu, mfano: Mama, Rafiki John', max_length=100)),
                ('identifier', models.CharField(help_text='Namba ya simu au barua pepe ya mpokeaji', max_length=255)),
                ('is_favorite', models.BooleanField(default=False)),
                ('linked_user', models.ForeignKey(blank=True, help_text='User halisi anayelingana na identifier, kama yupo kwenye mfumo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_of', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Mtumiaji aliyehifadhi mpokeaji huyu', on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beneficiary',
                'verbose_name_plural': 'Beneficiaries',
                'ordering': ['-is_favorite', 'name'],
                'unique_together': {('owner', 'identifier')},
            },
        ),
    ]
