# Generated by Django 4.2.16 on 2026-07-12 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jamiiwallet', '0008_beneficiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(blank=True, choices=[('FOOD', 'Chakula'), ('TRANSPORT', 'Usafiri'), ('RENT', 'Kodi ya Nyumba/Ofisi'), ('UTILITIES', 'Umeme/Maji/Mtandao'), ('SUPPLIES', 'Malighafi/Vifaa'), ('SALARIES', 'Mishahara'), ('TAX', 'Kodi ya Serikali'), ('HEALTH', 'Afya'), ('EDUCATION', 'Elimu'), ('OTHER', 'Nyingine')], help_text='Kundi la gharama linalofuatiliwa; tupu = bajeti ya jumla (makundi yote)', max_length=20, null=True)),
                ('period', models.CharField(choices=[('WEEKLY', 'Kila Wiki'), ('MONTHLY', 'Kila Mwezi'), ('YEARLY', 'Kila Mwaka')], default='MONTHLY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Kiwango cha juu cha matumizi', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('wallet', models.ForeignKey(help_text='Wallet inayohusika na bajeti hii', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='jamiiwallet.wallet')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('FOOD', 'Chakula'), ('TRANSPORT', 'Usafiri'), ('RENT', 'Kodi ya Nyumba/Ofisi'), ('UTILITIES', 'Umeme/Maji/Mtandao'), ('SUPPLIES', 'Malighafi/Vifaa'), ('SALARIES', 'Mishahara'), ('TAX', 'Kodi ya Serikali'), ('HEALTH', 'Afya'), ('EDUCATION', 'Elimu'), ('OTHER', 'Nyingine')], default='OTHER', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('incurred_at', models.DateField(default=django.utils.timezone.now, help_text='Tarehe halisi gharama ilipotokea (si tarehe ya kuandikwa)')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Aliyeandika gharama hii', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(help_text='Wallet inayohusika na gharama hii (ya mtu au ya biashara baadaye)', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='jamiiwallet.wallet')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-incurred_at', '-created_at'],
                'indexes': [models.Index(fields=['wallet', 'category', 'incurred_at'], name='jamiiwallet_wallet__457a47_idx')],
            },
        ),
    ]
