# Generated by Django 4.2.16 on 2026-07-12 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jamiiwallet', '0009_budget_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='incurred_at',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Tarehe halisi gharama ilipotokea (si tarehe ya kuandikwa)'),
        ),
    ]
