# Generated by Django 4.2.16 on 2026-07-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamiiwallet', '0010_alter_expense_incurred_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='held_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Kiasi kilichoshikiliwa (escrow) - hakiwezi kutumika mpaka kiachiliwe.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('TOP_UP', 'Top Up'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('HOLD', 'Hold'), ('CAPTURE', 'Capture'), ('VOID', 'Void')], max_length=20),
        ),
    ]
