# Generated by Django 4.2.16 on 2026-07-17 19:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('jamiiwallet', '0011_wallet_held_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_held', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_captured', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_voided', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('hold_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_hold', to='jamiiwallet.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_holds', to='jamiiwallet.wallet')),
            ],
            options={
                'verbose_name': 'Escrow Hold',
                'verbose_name_plural': 'Escrow Holds',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='jamiiwallet_content_c872d0_idx'), models.Index(fields=['wallet', 'status'], name='jamiiwallet_wallet__d5e40b_idx')],
            },
        ),
    ]
