# Generated by Django 4.2.16 on 2026-05-10 07:14

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import kiini.helpers.validators
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_datetime', models.DateTimeField(help_text='The date and time the service is booked for.', verbose_name='Scheduled Date & Time')),
                ('notes', models.TextField(blank=True, help_text='Additional instructions or information from the client.', verbose_name='Client Notes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, verbose_name='Booking Status')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Payment Status')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Actual Start Time')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Actual End Time')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Cancellation Reason')),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Reference')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_type', models.CharField(choices=[('CLIENT', 'Client'), ('OWNER', 'Business Owner'), ('STAFF', 'Business Staff'), ('SYSTEM', 'System')], default='SYSTEM', help_text='What role performed this action (Client, Owner, Staff, System)?', max_length=20, verbose_name='Actor Type')),
                ('action', models.CharField(help_text='Action performed on the booking (e.g., CREATED, CONFIRMED, CANCELLED).', max_length=30, verbose_name='Action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context or data related to the action.', verbose_name='Additional Context or Data')),
            ],
            options={
                'verbose_name': 'Booking Log',
                'verbose_name_plural': 'Booking Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text='Jina la tawi la biashara.', max_length=255, verbose_name='Branch Name')),
                ('description', models.TextField(blank=True, help_text='Maelezo mafupi kuhusu tawi hili.', verbose_name='Description')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Mahali ambapo tawi hili linapatikana (latitude/longitude).', null=True, srid=4326, verbose_name='Location')),
                ('phone', models.CharField(blank=True, help_text='Nambari ya simu ya mawasiliano ya tawi.', max_length=30, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, help_text='Barua pepe ya tawi (si lazima).', max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, help_text='Je, tawi hili linafanya kazi kwa sasa?', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Namba ya simu ya kimataifa (Mfano: +255...).', max_length=128, null=True, region=None, validators=[kiini.helpers.validators.validate_eac_phone], verbose_name='Phone')),
                ('is_phone_verified', models.BooleanField(default=False, help_text='Je namba hii ya simu imethibitishwa kwa SMS?', verbose_name='Phone Verified')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Location')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('description', models.TextField(blank=True, help_text='Maelezo mafupi kuhusu biashara.', verbose_name='Description')),
                ('website', models.URLField(blank=True, help_text='Tovuti rasmi ya biashara (kama ipo).', verbose_name='Website')),
                ('is_verified', models.BooleanField(default=False, help_text='Je biashara hii imethibitishwa rasmi?', verbose_name='Is Verified')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the business name.', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text='Jina la aina ya biashara, mfano: Mgahawa, Duka, Kliniki.', max_length=255, verbose_name='Category Name')),
                ('name_en', models.CharField(help_text='Jina la aina ya biashara, mfano: Mgahawa, Duka, Kliniki.', max_length=255, null=True, verbose_name='Category Name')),
                ('name_sw', models.CharField(help_text='Jina la aina ya biashara, mfano: Mgahawa, Duka, Kliniki.', max_length=255, null=True, verbose_name='Category Name')),
                ('name_fr', models.CharField(help_text='Jina la aina ya biashara, mfano: Mgahawa, Duka, Kliniki.', max_length=255, null=True, verbose_name='Category Name')),
                ('name_ar', models.CharField(help_text='Jina la aina ya biashara, mfano: Mgahawa, Duka, Kliniki.', max_length=255, null=True, verbose_name='Category Name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier, mfano: mgahawa, duka-la-kiatu.', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya biashara.', null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya biashara.', null=True, verbose_name='Description')),
                ('description_sw', models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya biashara.', null=True, verbose_name='Description')),
                ('description_fr', models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya biashara.', null=True, verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya biashara.', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Business Category',
                'verbose_name_plural': 'Business Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20, verbose_name='Order Status')),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20, verbose_name='Payment Status')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Sum of all order items.', max_digits=10, verbose_name='Total Amount')),
                ('notes', models.TextField(blank=True, verbose_name='Order Notes')),
                ('scheduled_datetime', models.DateTimeField(blank=True, help_text='For scheduled services or deliveries.', null=True, verbose_name='Scheduled Date & Time')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text='Jina la bidhaa.', max_length=255, verbose_name='Product Name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier ya bidhaa.', max_length=300, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Maelezo ya bidhaa hii.', verbose_name='Description')),
                ('type', models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital'), ('service', 'Service')], default='physical', help_text='Aina ya bidhaa: Physical, Digital, au Service.', max_length=20, verbose_name='Product Type')),
                ('price', models.DecimalField(decimal_places=2, help_text='Bei ya kawaida ya bidhaa.', max_digits=12, verbose_name='Price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Bei ya punguzo ikiwa ipo.', max_digits=12, null=True, verbose_name='Discount Price')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, help_text='Idadi ya bidhaa zilizopo stock.', verbose_name='Stock Quantity')),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Litres'), ('ml', 'Millilitres'), ('box', 'Box'), ('pack', 'Pack'), ('dozen', 'Dozen'), ('pair', 'Pair'), ('set', 'Set'), ('m', 'Meter'), ('cm', 'Centimeter'), ('hour', 'Hour'), ('day', 'Day'), ('session', 'Session')], default='pcs', help_text='Kipimo cha bidhaa.', max_length=20, verbose_name='Unit')),
                ('is_available', models.BooleanField(default=True, help_text='Inaonesha kama bidhaa ipo sokoni au la.', verbose_name='Is Available')),
                ('is_featured', models.BooleanField(default=False, help_text='Inaonesha kama bidhaa ni ya kipekee (featured).', verbose_name='Is Featured')),
                ('image', models.ImageField(blank=True, help_text='Picha kuu ya bidhaa.', null=True, upload_to='products/images/', verbose_name='Product Image')),
                ('additional_images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, help_text='Picha nyingine za bidhaa (URL links).', null=True, size=None, verbose_name='Additional Images')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Maneno muhimu au majina ya aina ya bidhaa.', size=None, verbose_name='Tags / Keywords')),
                ('tax_inclusive', models.BooleanField(default=True, help_text='Inaonesha kama bei inajumuisha VAT.', verbose_name='Price includes VAT')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Kiwango cha VAT kilichojumuishwa, kwa asilimia.', max_digits=5, verbose_name='Tax Rate (%)')),
                ('external_link', models.URLField(blank=True, help_text='Link ya kununua bidhaa kutoka nje ya mfumo huu (optional).', null=True, verbose_name='External Link / Purchase Link')),
                ('digital_file', models.FileField(blank=True, help_text='Faili la bidhaa za kidigitali (ikiwa ni Digital Product).', null=True, upload_to='products/files/', verbose_name='Digital File')),
                ('language_code', models.CharField(choices=[('sw', 'Swahili'), ('en', 'English'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Lugha inayotumika kwenye maelezo ya bidhaa.', max_length=10, verbose_name='Language')),
                ('business', models.ForeignKey(help_text='Biashara inayomiliki bidhaa hii.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='businesses.business', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text='Jina la huduma.', max_length=255, verbose_name='Service Name')),
                ('description', models.TextField(blank=True, help_text='Maelezo ya huduma.', verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Gharama ya huduma.', max_digits=12, verbose_name='Price')),
                ('billing_type', models.CharField(choices=[('ONE_TIME', 'One-time'), ('HOURLY', 'Per Hour'), ('DAILY', 'Per Day'), ('WEEKLY', 'Per Week'), ('MONTHLY', 'Per Month')], default='ONE_TIME', help_text='Jinsi malipo yanavyofanyika: kwa mara moja, kwa saa, au muda mwingine.', max_length=20, verbose_name='Billing Type')),
                ('location_type', models.CharField(choices=[('PROVIDER', 'At Provider Location'), ('CLIENT', 'At Client Location'), ('REMOTE', 'Remote / Online')], default='PROVIDER', help_text='Mahali pa kutolea huduma: kwa mtoa huduma, kwa mteja, au mtandaoni.', max_length=20, verbose_name='Service Location Type')),
                ('requires_booking', models.BooleanField(default=False, help_text='Inaonesha kama huduma inahitaji kuweka miadi (booking).', verbose_name='Requires Booking')),
                ('is_available', models.BooleanField(default=True, help_text='Huduma inapatikana kwa sasa.', verbose_name='Is Available')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Muda wa makadirio kwa huduma hii kwa dakika.', null=True, verbose_name='Duration (Minutes)')),
                ('business', models.ForeignKey(help_text='Biashara inayotoa huduma hii.', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='businesses.business', verbose_name='Business')),
                ('category', models.ForeignKey(blank=True, help_text='Aina ya huduma au biashara inayohusiana.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.businesscategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Chagua alama (1 hadi 5) kulingana na uzoefu wako.', verbose_name='Rating')),
                ('content', models.TextField(help_text='Andika maoni yako kuhusu huduma/bidhaa/biashara.', verbose_name='Review Content')),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Tiki kama review hii imepitishwa na admin.', verbose_name='Is Approved')),
                ('business', models.ForeignKey(blank=True, help_text='Chagua kama review hii ni ya biashara fulani.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='businesses.business', verbose_name='Business')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('product', models.ForeignKey(blank=True, help_text='Chagua kama review hii ni ya bidhaa fulani.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='businesses.product', verbose_name='Product')),
                ('service', models.ForeignKey(blank=True, help_text='Chagua kama review hii ni ya huduma fulani.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='businesses.service', verbose_name='Service')),
                ('user', models.ForeignKey(help_text='Mteja anayetoa tathmini hii.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
