# Generated by Django 4.2.16 on 2026-05-10 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('businesses', '0001_initial'),
        ('kiini', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Sarafu ya bei ya bidhaa.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='payments.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='businesses.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='businesses.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='businesses.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='order',
            name='business',
            field=models.ForeignKey(help_text='Business that received the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='businesses.business', verbose_name='Business'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(help_text='User who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='businesses.businesscategory'),
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Aina au sekta ya biashara.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='businesses.businesscategory', verbose_name='Business Category'),
        ),
        migrations.AddField(
            model_name='business',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Taasisi inayosimamia biashara hii.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='kiini.institution', verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='branch',
            name='business',
            field=models.ForeignKey(help_text='Biashara inayomiliki tawi hili.', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='businesses.business', verbose_name='Business'),
        ),
        migrations.AddField(
            model_name='branch',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Huduma zinazotolewa katika tawi hili.', related_name='branches', to='businesses.service', verbose_name='Services at Branch'),
        ),
        migrations.AddField(
            model_name='bookinglog',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='businesses.booking', verbose_name='Booking'),
        ),
        migrations.AddField(
            model_name='bookinglog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='businesses.service', verbose_name='Service'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='businesses__slug_e51015_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tags'], name='businesses__tags_62e735_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('product__isnull', False), ('service__isnull', False), _connector='OR'), name='order_item_product_or_service_not_null'),
        ),
        migrations.AddIndex(
            model_name='bookinglog',
            index=models.Index(fields=['booking', 'action'], name='businesses__booking_102ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinglog',
            index=models.Index(fields=['actor_type'], name='businesses__actor_t_b3d53c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinglog',
            index=models.Index(fields=['created_at'], name='businesses__created_ba6c49_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'payment_status'], name='businesses__status_a8036a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['scheduled_datetime'], name='businesses__schedul_3038b3_idx'),
        ),
    ]
