# Generated by Django 4.2.16 on 2026-07-12 19:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Maneno muhimu ya ziada ya kutafutia bidhaa (si badala ya category).', size=None, verbose_name='Tags / Keywords'),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text='Jina la aina ya bidhaa, mfano: Vyakula, Vinywaji, Nguo.', max_length=255, verbose_name='Category Name')),
                ('name_en', models.CharField(help_text='Jina la aina ya bidhaa, mfano: Vyakula, Vinywaji, Nguo.', max_length=255, null=True, verbose_name='Category Name')),
                ('name_sw', models.CharField(help_text='Jina la aina ya bidhaa, mfano: Vyakula, Vinywaji, Nguo.', max_length=255, null=True, verbose_name='Category Name')),
                ('name_fr', models.CharField(help_text='Jina la aina ya bidhaa, mfano: Vyakula, Vinywaji, Nguo.', max_length=255, null=True, verbose_name='Category Name')),
                ('name_ar', models.CharField(help_text='Jina la aina ya bidhaa, mfano: Vyakula, Vinywaji, Nguo.', max_length=255, null=True, verbose_name='Category Name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier, mfano: vyakula, vinywaji.', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya bidhaa.', null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya bidhaa.', null=True, verbose_name='Description')),
                ('description_sw', models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya bidhaa.', null=True, verbose_name='Description')),
                ('description_fr', models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya bidhaa.', null=True, verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya bidhaa.', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='businesses.productcategory')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Aina/kabati la bidhaa hii, mfano: Vyakula, Vinywaji, Nguo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='businesses.productcategory', verbose_name='Category'),
        ),
    ]
