# Generated by Django 4.2.16 on 2026-07-13 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesses', '0003_alter_product_tags_productcategory_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('placement', models.CharField(choices=[('HOMEPAGE', 'Homepage - Bidhaa/Matangazo Yaliyodhaminiwa')], default='HOMEPAGE', max_length=20, verbose_name='Placement')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Kiasi kilicholipwa/kinachotakiwa kulipwa kwa matangazo haya.', max_digits=12, verbose_name='Amount')),
                ('is_active', models.BooleanField(default=False, help_text='Inakuwa True baada ya invoice kulipwa - ndipo inaonekana kwenye homepage.', verbose_name='Is Active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_listings', to='businesses.business', verbose_name='Business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_listings_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_listings', to='payments.invoice', verbose_name='Invoice')),
                ('product', models.ForeignKey(blank=True, help_text='Bidhaa maalum ya kutangaza (hiari - kama tupu, biashara nzima ndiyo inayotangazwa).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_listings', to='businesses.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Featured Listing',
                'verbose_name_plural': 'Featured Listings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'start_date', 'end_date'], name='businesses__is_acti_d62cfc_idx')],
            },
        ),
    ]
