# Generated by Django 4.2.16 on 2026-07-14 21:38

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesses', '0004_featuredlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bei ya usafiri, inajumuishwa kwenye total_amount kama fulfillment_type ni DELIVERY.', max_digits=10, verbose_name='Delivery Fee'),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_type',
            field=models.CharField(choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], default='PICKUP', max_length=20, verbose_name='Fulfillment Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('HELD', 'Held'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_name_query', models.CharField(help_text='Maneno aliyotafuta mnunuzi - kwa ajili ya rekodi/uchambuzi tu.', max_length=255, verbose_name='Search Query')),
                ('matched_product_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, help_text='Snapshot ya Product IDs zilizolingana wakati ombi lilipotumwa.', size=None)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Buyer Location')),
                ('address_text', models.CharField(blank=True, max_length=255)),
                ('radius_km', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('FULFILLED', 'Fulfilled'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_requests', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_requests', to='businesses.productcategory')),
                ('claimed_by_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_item_requests', to='businesses.business')),
                ('claimed_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_item_requests', to='businesses.product')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_request', to='businesses.order')),
            ],
            options={
                'verbose_name': 'Item Request',
                'verbose_name_plural': 'Item Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='businesses__status_ae914f_idx')],
            },
        ),
    ]
