# Generated by Django 4.2.16 on 2026-07-15 15:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_order_delivery_fee_order_fulfillment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Idadi ya bidhaa zilizopo stock (inaweza kuwa na desimali kwa vipimo kama kg, l, m).', max_digits=12, verbose_name='Stock Quantity'),
        ),
    ]
