# Generated by Django 4.2.16 on 2026-07-16 14:34

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_auditlog_action'),
        ('businesses', '0006_alter_itemrequest_quantity_alter_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.OneToOneField(blank=True, help_text='Invoice ya malipo ya mkopo - imewekwa tu kama payment_terms != IMMEDIATE.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_order', to='payments.invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_terms',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('NET_15', 'Net 15'), ('NET_30', 'Net 30')], default='IMMEDIATE', help_text='NET_15/NET_30 zinapatikana tu kwa purchasing_business yenye mkopo (BusinessCreditAccount) - vinginevyo IMMEDIATE pekee.', max_length=20, verbose_name='Payment Terms'),
        ),
        migrations.AddField(
            model_name='order',
            name='purchasing_business',
            field=models.ForeignKey(blank=True, help_text="Biashara inayonunua (B2B) - imewekwa tu client anaponunua 'kama biashara yake', si mtu binafsi. Null = ununuzi wa kawaida wa rejareja, tabia haibadiliki kabisa.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='businesses.business', verbose_name='Purchasing Business'),
        ),
        migrations.CreateModel(
            name='ProductPriceTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('min_quantity', models.DecimalField(decimal_places=3, help_text='Kiasi cha chini (MOQ) kinachohitajika kupata bei hii.', max_digits=12, verbose_name='Minimum Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Bei ya kitengo kimoja ukinunua angalau min_quantity.', max_digits=12, verbose_name='Unit Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='businesses.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Price Tier',
                'verbose_name_plural': 'Product Price Tiers',
                'ordering': ['min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='BusinessCreditAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Credit Limit')),
                ('outstanding_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Outstanding Credit')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='businesses.business', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Business Credit Account',
                'verbose_name_plural': 'Business Credit Accounts',
            },
        ),
        migrations.AddConstraint(
            model_name='productpricetier',
            constraint=models.UniqueConstraint(fields=('product', 'min_quantity'), name='unique_tier_per_quantity'),
        ),
    ]
