# Generated by Django 4.2.16 on 2026-07-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_order_invoice_order_payment_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Litres'), ('ml', 'Millilitres'), ('box', 'Box'), ('pack', 'Pack'), ('dozen', 'Dozen'), ('pair', 'Pair'), ('set', 'Set'), ('m', 'Meter'), ('cm', 'Centimeter'), ('hour', 'Hour'), ('day', 'Day'), ('session', 'Session'), ('gunia', 'Gunia (Sack)'), ('debe', 'Debe (~20L Tin)'), ('fungu', 'Fungu (Bundle)'), ('roli', 'Roli (Roll)'), ('bale', 'Bale (Mtumba)')], default='pcs', help_text='Kipimo cha bidhaa.', max_length=20, verbose_name='Unit'),
        ),
    ]
