# Generated by Django 4.2.16 on 2026-07-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('WALLET', 'JamiiWallet'), ('CASH', 'Cash')], default='WALLET', help_text='CASH inaruhusiwa tu kwa PICKUP na biashara iliyothibitishwa (is_verified) - fedha hazishikiliwi (escrow), mnunuzi analipa taslimu akichukua bidhaa.', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('HELD', 'Held'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CASH_PENDING', 'Cash Pending')], default='UNPAID', max_length=20, verbose_name='Payment Status'),
        ),
    ]
