# Generated by Django 4.2.16 on 2026-07-16 20:56

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesses', '0009_order_payment_method_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='broker_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Asilimia ya kamisheni kwa dalali aliyeleta mnunuzi - 0 (default) inamaanisha hakuna kamisheni, kipengele hiki hakina athari kabisa mpaka mmiliki wa biashara akiweka kiwango zaidi ya sifuri.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Broker Commission Rate (%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='Dalali aliyeleta mnunuzi kwenye oda hii (kwa msimbo wa rufaa) - null = ununuzi wa kawaida bila dalali, tabia haibadiliki kabisa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_orders', to=settings.AUTH_USER_MODEL, verbose_name='Referred By'),
        ),
    ]
