# Generated by Django 4.2.16 on 2026-07-17 12:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesses', '0011_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='deals_in_imports',
            field=models.BooleanField(default=False, help_text='Biashara hii inaweza kuagiza bidhaa kutoka nje ya nchi - itaona maombi ya uagizaji (import requests) kutoka kwa wanunuzi.', verbose_name='Deals in Imports'),
        ),
        migrations.CreateModel(
            name='ImportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_description', models.TextField(help_text='Maelezo ya bidhaa inayotakiwa kuagizwa - jina, aina, spesifikesheni.', verbose_name='Item Description')),
                ('origin_country', models.CharField(blank=True, max_length=100, verbose_name='Origin Country')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Budget Amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('FULFILLED', 'Fulfilled'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('claimed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Claimed Price')),
                ('estimated_lead_days', models.PositiveIntegerField(blank=True, help_text='Makadirio ya siku za kusubiri bidhaa ifike - si ufuatiliaji halisi wa usafirishaji.', null=True, verbose_name='Estimated Lead Days')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('budget_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_requests', to='payments.currency')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_requests', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('claimed_by_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_import_requests', to='businesses.business')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_request', to='businesses.order')),
            ],
            options={
                'verbose_name': 'Import Request',
                'verbose_name_plural': 'Import Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='businesses__status_e41471_idx')],
            },
        ),
    ]
