# Generated by Django 4.2.16 on 2026-07-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0012_business_deals_in_imports_importrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='license_number_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
