# Generated by Django 4.2.16 on 2026-07-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0013_business_license_number_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='deals_in_agriculture',
            field=models.BooleanField(default=False, help_text='Biashara hii inaweza kusambaza mazao ya kilimo kwa wingi - itaona mikataba ya awali ya mazao (harvest contracts) kutoka kwa wanunuzi.', verbose_name='Deals in Agriculture'),
        ),
    ]
