# Generated by Django 4.2.16 on 2026-07-18 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0014_business_deals_in_agriculture'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='domain',
            field=models.CharField(blank=True, help_text='Sehemu ya kwanza ya anwani ya duka lako: <domain>.jamiikazini.com', max_length=63, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Domain lazima iwe herufi ndogo, namba, na hyphen pekee (mfano: mama-lishe).', regex='^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$')], verbose_name='Subdomain'),
        ),
    ]
