# Generated by Django 4.2.16 on 2026-07-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0015_business_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='description_af',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya biashara.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='description_es',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya biashara.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='description_ha',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya biashara.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='description_hi',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya biashara.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='description_ja',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya biashara.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='description_ko',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya biashara.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='description_lg',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya biashara.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='description_pt',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya biashara.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya biashara.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='description_rw',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya biashara.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='description_zh',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya biashara.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='name_af',
            field=models.CharField(help_text='Jina la aina ya biashara, mfano: Mgahawa, Duka, Kliniki.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='name_es',
            field=models.CharField(help_text='Jina la aina ya biashara, mfano: Mgahawa, Duka, Kliniki.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='name_ha',
            field=models.CharField(help_text='Jina la aina ya biashara, mfano: Mgahawa, Duka, Kliniki.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='name_hi',
            field=models.CharField(help_text='Jina la aina ya biashara, mfano: Mgahawa, Duka, Kliniki.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='name_ja',
            field=models.CharField(help_text='Jina la aina ya biashara, mfano: Mgahawa, Duka, Kliniki.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='name_ko',
            field=models.CharField(help_text='Jina la aina ya biashara, mfano: Mgahawa, Duka, Kliniki.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='name_lg',
            field=models.CharField(help_text='Jina la aina ya biashara, mfano: Mgahawa, Duka, Kliniki.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='name_pt',
            field=models.CharField(help_text='Jina la aina ya biashara, mfano: Mgahawa, Duka, Kliniki.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='name_ru',
            field=models.CharField(help_text='Jina la aina ya biashara, mfano: Mgahawa, Duka, Kliniki.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='name_rw',
            field=models.CharField(help_text='Jina la aina ya biashara, mfano: Mgahawa, Duka, Kliniki.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='name_zh',
            field=models.CharField(help_text='Jina la aina ya biashara, mfano: Mgahawa, Duka, Kliniki.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_af',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya bidhaa.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_es',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya bidhaa.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_ha',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya bidhaa.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_hi',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya bidhaa.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_ja',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya bidhaa.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_ko',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya bidhaa.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_lg',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya bidhaa.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_pt',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya bidhaa.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya bidhaa.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_rw',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya bidhaa.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_zh',
            field=models.TextField(blank=True, help_text='Maelezo ya ziada kuhusu aina hii ya bidhaa.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_af',
            field=models.CharField(help_text='Jina la aina ya bidhaa, mfano: Vyakula, Vinywaji, Nguo.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_es',
            field=models.CharField(help_text='Jina la aina ya bidhaa, mfano: Vyakula, Vinywaji, Nguo.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_ha',
            field=models.CharField(help_text='Jina la aina ya bidhaa, mfano: Vyakula, Vinywaji, Nguo.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_hi',
            field=models.CharField(help_text='Jina la aina ya bidhaa, mfano: Vyakula, Vinywaji, Nguo.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_ja',
            field=models.CharField(help_text='Jina la aina ya bidhaa, mfano: Vyakula, Vinywaji, Nguo.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_ko',
            field=models.CharField(help_text='Jina la aina ya bidhaa, mfano: Vyakula, Vinywaji, Nguo.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_lg',
            field=models.CharField(help_text='Jina la aina ya bidhaa, mfano: Vyakula, Vinywaji, Nguo.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_pt',
            field=models.CharField(help_text='Jina la aina ya bidhaa, mfano: Vyakula, Vinywaji, Nguo.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_ru',
            field=models.CharField(help_text='Jina la aina ya bidhaa, mfano: Vyakula, Vinywaji, Nguo.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_rw',
            field=models.CharField(help_text='Jina la aina ya bidhaa, mfano: Vyakula, Vinywaji, Nguo.', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_zh',
            field=models.CharField(help_text='Jina la aina ya bidhaa, mfano: Vyakula, Vinywaji, Nguo.', max_length=255, null=True, verbose_name='Category Name'),
        ),
    ]
