# Generated by Django 4.2.16 on 2026-08-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0017_remove_product_additional_images_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_subscription',
            field=models.BooleanField(default=False, help_text="Bidhaa hii ni huduma ya usajili unaoendelea (si manunuzi ya mara moja) - `price` bado inaonesha ada halisi, lakini kwenye orodha za umma (Sponsored Ads, Trending) inaonyeshwa kitufe cha 'Pata'/'Omba' badala ya bei moja kwa moja.", verbose_name='Is Subscription'),
        ),
    ]
