# Generated by Django 4.2.16 on 2026-05-10 07:14

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import kiini.helpers.validators
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(choices=[('MICRO', 'Micro Enterprise'), ('SMALL', 'Small Enterprise'), ('MEDIUM', 'Medium Enterprise'), ('LARGE', 'Large Enterprise'), ('ENTERPRISE', 'Corporate / Enterprise')], max_length=20, unique=True, verbose_name='Tier Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Institution Tier',
                'verbose_name_plural': 'Institution Tiers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(choices=[('PRIMARY_SCHOOL', 'Primary School'), ('SECONDARY_SCHOOL', 'Secondary School'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University'), ('VTC', 'Vocational Training Center'), ('HOSPITAL', 'Hospital'), ('HEALTH_CENTER', 'Health Center'), ('DISPENSARY', 'Dispensary'), ('CLINIC', 'Clinic'), ('NGO', 'Non-Governmental Organization'), ('CBO', 'Community-Based Organization'), ('FBO', 'Faith-Based Organization'), ('PRIVATE_COMPANY', 'Private Company'), ('PUBLIC_CORPORATION', 'Public Corporation'), ('COOPERATIVE', 'Cooperative Society'), ('GOVERNMENT_MINISTRY', 'Government Ministry'), ('MUNICIPAL_COUNCIL', 'Municipal Council'), ('PARASTATAL', 'Parastatal Organization'), ('RELIGIOUS_INSTITUTION', 'Religious Institution'), ('TRAINING_INSTITUTE', 'Training Institute')], max_length=50, unique=True, verbose_name='Type Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Institution Type',
                'verbose_name_plural': 'Institution Types',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Namba ya simu ya kimataifa (Mfano: +255...).', max_length=128, null=True, region=None, validators=[kiini.helpers.validators.validate_eac_phone], verbose_name='Phone')),
                ('is_phone_verified', models.BooleanField(default=False, help_text='Je namba hii ya simu imethibitishwa kwa SMS?', verbose_name='Phone Verified')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Location')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('domain', models.CharField(help_text='Mfano: institution_name.jamiikazini.com', max_length=255, unique=True, verbose_name='Domain')),
                ('metadata', models.JSONField(blank=True, help_text='Taarifa za ziada kama config au settings.', null=True, verbose_name='Metadata')),
                ('institution_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='kiini.institutiontype', verbose_name='Institution Type')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='kiini.institutiontier', verbose_name='Tier')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255, verbose_name='Department Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='kiini.institution', verbose_name='Institution')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ('institution__name', 'name'),
                'unique_together': {('institution', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Position')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='kiini.department', verbose_name='Department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to='kiini.institution', verbose_name='Institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'ordering': ('institution', 'user'),
                'unique_together': {('user', 'institution')},
            },
        ),
    ]
