# Generated by Django 5.2.15 on 2026-07-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='domain',
            field=models.CharField(blank=True, help_text='Mfano: institution_name.jamiikazini.com', max_length=255, null=True, unique=True, verbose_name='Domain'),
        ),
    ]
