# Generated by Django 4.2.16 on 2026-07-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiini', '0003_referralcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('CHAT', 'Chat'), ('PAYMENT', 'Payment'), ('REQUEST', 'Request'), ('SYSTEM', 'System')], default='SYSTEM', max_length=10),
        ),
    ]
