# Generated by Django 4.2.16 on 2026-07-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiini', '0004_notification_link_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='domain',
            field=models.CharField(blank=True, help_text="Sehemu ya kwanza TU ya subdomain (mfano: 'shule-yangu'), SIO domain kamili - taasisi inapatikana kwenye https://<domain>.jamiikazini.com. Lazima ilingane na kile InstitutionMiddleware inachotafuta (parts[0] ya host).", max_length=255, null=True, unique=True, verbose_name='Subdomain'),
        ),
    ]
