# Generated by Django 4.2.16 on 2026-08-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiini', '0005_alter_institution_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, help_text='Shown to locked-out users. Leave blank to use the default notice.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform lock',
                'verbose_name_plural': 'Platform lock',
            },
        ),
    ]
