# Generated by Django 4.2.16 on 2026-07-17 20:07

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0005_alter_auditlog_action'),
        ('jamiiwallet', '0012_escrowhold'),
        ('businesses', '0013_business_license_number_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('listing_type', models.CharField(choices=[('RENT', 'For Rent'), ('SALE', 'For Sale')], max_length=10)),
                ('property_type', models.CharField(choices=[('LAND', 'Land'), ('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('COMMERCIAL', 'Commercial')], max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('address_text', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('lease_duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('title_deed_number', models.CharField(blank=True, help_text='Namba ya hati - imetolewa na muuzaji mwenyewe, HAIJATHIBITISHWA na ardhi.go.tz.', max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('RENTED', 'Rented'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_listings', to='payments.currency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_listings', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Property Listing',
                'verbose_name_plural': 'Property Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESERVED', 'Reserved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_inquiries', to=settings.AUTH_USER_MODEL)),
                ('escrow_hold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_inquiry', to='jamiiwallet.escrowhold')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='realestate.propertylisting')),
            ],
            options={
                'verbose_name': 'Property Inquiry',
                'verbose_name_plural': 'Property Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='properties/images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='realestate.propertylisting')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['status'], name='realestate__status_0b4427_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['listing_type', 'property_type'], name='realestate__listing_575b78_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinquiry',
            index=models.Index(fields=['status'], name='realestate__status_4bb12f_idx'),
        ),
    ]
