# Generated by Django 4.2.16 on 2026-07-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_identity_verified',
            field=models.BooleanField(default=False, help_text='Set only by a completed government NIDA/national-ID verification (gov_integration.NationalIDVerificationSerializer). Distinct from is_verified, which is also flipped by plain email verification.'),
        ),
    ]
