# Generated by Django 4.2.16 on 2026-07-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_identity_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
