# Generated by Django 4.2.16 on 2026-07-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backfill_national_id_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text='Set only by a completed SMS OTP challenge to this exact phone number (security.views.phone_verification_views). Symmetric with is_verified (email link) - together with is_identity_verified, gates IsIdentityVerified (accounts.permissions).'),
        ),
    ]
