# Generated by Django 4.2.16 on 2026-07-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_dropoff_address_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='last_dropoff_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_dropoff_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
