# Generated by Django 4.2.16 on 2026-07-18 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jamiiwallet', '0012_escrowhold'),
        ('businesses', '0014_business_deals_in_agriculture'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('crop_description', models.CharField(max_length=255)),
                ('estimated_weight_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('agreed_price_per_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_window_start', models.DateField()),
                ('delivery_window_end', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('SETTLED', 'Settled'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('buyer_confirmed_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('buyer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('seller_confirmed_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('seller_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_contracts_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('escrow_hold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_contract', to='jamiiwallet.escrowhold')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_contracts_as_seller', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Harvest Contract',
                'verbose_name_plural': 'Harvest Contracts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='agriculture_status_d5d4c9_idx')],
            },
        ),
    ]
