# Generated by Django 4.2.16 on 2026-05-10 07:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, editable=False, help_text='Ordering of class levels, auto-incremented', null=True)),
            ],
            options={
                'verbose_name': 'Class Level',
                'verbose_name_plural': 'Class Levels',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonSentence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('intro', 'Utangulizi / Introduction'), ('development', 'Kuimarisha / Development'), ('conclusion', 'Hitimisho / Conclusion'), ('reflection', 'Maoni / Reflection')], default='intro', max_length=20)),
                ('language', models.CharField(choices=[('sw', 'Swahili'), ('en', 'English')], default='sw', max_length=2)),
                ('is_awali', models.BooleanField(default=False, help_text='True kwa darasa la Awali')),
                ('is_active', models.BooleanField(default=True)),
                ('teaching_sw', models.TextField(blank=True, default='')),
                ('learning_sw', models.TextField(blank=True, default='')),
                ('indicator_primary_sw', models.TextField(blank=True, default='')),
                ('indicator_secondary_sw', models.TextField(blank=True, default='')),
                ('teaching_en', models.TextField(blank=True, default='')),
                ('learning_en', models.TextField(blank=True, default='')),
                ('indicator_primary_en', models.TextField(blank=True, default='')),
                ('indicator_secondary_en', models.TextField(blank=True, default='')),
                ('reflection_sw', models.TextField(blank=True, default='')),
                ('reflection_comment_sw', models.TextField(blank=True, default='')),
                ('reflection_en', models.TextField(blank=True, default='')),
                ('reflection_comment_en', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['category', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MainCompetence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.TextField(help_text='Name/description of the main competence')),
                ('order', models.PositiveIntegerField(blank=True, editable=False, help_text='Order of main competences within a SubjectVersion', null=True)),
            ],
            options={
                'verbose_name': 'Main Competence',
                'verbose_name_plural': 'Main Competences',
                'ordering': ['subject_version', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('periods_per_week', models.PositiveSmallIntegerField(default=1, help_text='Number of periods per week for this subject')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_english', models.BooleanField(default=False, help_text='Marks if this subject version belongs to the English-medium syllabus')),
                ('is_awali', models.BooleanField(default=False, help_text='Marks if this subject version is for Awali curriculum')),
                ('order', models.PositiveIntegerField(blank=True, editable=False, help_text='Order of subjects within syllabus_version + class_level', null=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_versions', to='syllabus.classlevel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='syllabus.subject')),
            ],
            options={
                'verbose_name': 'Subject Version',
                'verbose_name_plural': 'Subject Versions',
                'ordering': ['syllabus_version__year', 'class_level__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.PositiveIntegerField(unique=True)),
                ('evaluation_aid', models.TextField(blank=True, help_text="Maelezo kuhusu vifaa au njia za evaluation. Mfano: 'Quiz, Assignment, Class Observation.'", verbose_name='Evaluation Aid')),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Syllabus Version',
                'verbose_name_plural': 'Syllabus Versions',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='TeacherWorkStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('school_name', models.CharField(help_text="2. Jina la shule ambapo mwalimu anafanya kazi. Mfano: 'Shule ya Msingi Mzingi'", max_length=255)),
                ('district', models.CharField(help_text="3. Jina la wilaya. Mfano: 'Halimashauri ya Wilaya ya Mkinga'", max_length=255)),
                ('ward', models.CharField(blank=True, help_text="4. Jina la kata (hiari). Mfano: 'Kata ya Parungu Kasera'", max_length=255, null=True)),
                ('region', models.CharField(blank=True, help_text="5. Jina la mkoa (hiari). Mfano: 'Tanga'", max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='6. Weka False ikiwa mwalimu hafanyi kazi tena hapa. Mfano: False')),
                ('teacher', models.OneToOneField(help_text="1. Chagua mwalimu anayehusiana na workstation hii. Mfano: 'ryoba.dennis@jamiikazini.com'", on_delete=django.db.models.deletion.CASCADE, related_name='workstation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sehemu ya Kazi ya Mwalimu',
                'verbose_name_plural': 'Sehemu za Kazi za Walimu',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('period', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, help_text='Chagua kipindi cha siku ambacho somo litafundishwa.', null=True, verbose_name='Kipindi')),
                ('timestart', models.TimeField(blank=True, default=django.utils.timezone.now, help_text='Weka muda wa kuanza wa kipindi.', null=True, verbose_name='Muda wa Kuanza')),
                ('timefinish', models.TimeField(blank=True, default=django.utils.timezone.now, help_text='Weka muda wa kuisha wa kipindi.', null=True, verbose_name='Muda wa Kumaliza')),
                ('registeredboys', models.IntegerField(blank=True, help_text='Andika idadi ya wavulana walioandikishwa darasani.', null=True, verbose_name='Idadi ya Wavulana')),
                ('registeredgirls', models.IntegerField(blank=True, help_text='Andika idadi ya wasichana walioandikishwa darasani.', null=True, verbose_name='Idadi ya Wasichana')),
                ('status', models.BooleanField(default=False, help_text='Weka True ikiwa mwalimu amethibitisha ratiba hii.', verbose_name='Imehakikishwa')),
                ('subject_version', models.ForeignKey(help_text='Chagua toleo la somo litakalofundishwa katika kipindi hiki. Hii inaonyesha darasa na syllabus version.', on_delete=django.db.models.deletion.CASCADE, to='syllabus.subjectversion', verbose_name='Somo (Version)')),
                ('workstation', models.ForeignKey(help_text='Chagua kituo cha kazi cha mwalimu. Hii itahusisha shule na halmashauri automatically.', on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='syllabus.teacherworkstation', verbose_name='Kituo cha Mwalimu')),
            ],
            options={
                'verbose_name': 'Ratiba ya Mwalimu',
                'verbose_name_plural': 'Ratiba za Walimu',
                'ordering': ['workstation', 'subject_version', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subjectversion',
            name='syllabus_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_versions', to='syllabus.syllabusversion'),
        ),
        migrations.CreateModel(
            name='SpecificCompetence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.TextField(help_text='Description of the specific competence')),
                ('order', models.PositiveIntegerField(blank=True, editable=False, help_text='Order of specific competences within a MainCompetence', null=True)),
                ('main_competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_competences', to='syllabus.maincompetence')),
            ],
            options={
                'verbose_name': 'Specific Competence',
                'verbose_name_plural': 'Specific Competences',
                'ordering': ['main_competence', 'order'],
                'unique_together': {('main_competence', 'name')},
            },
        ),
        migrations.AddField(
            model_name='maincompetence',
            name='subject_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_competences', to='syllabus.subjectversion'),
        ),
        migrations.CreateModel(
            name='LearningActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.TextField(help_text='Description of the learning activity')),
                ('order', models.PositiveIntegerField(blank=True, editable=False, help_text='Order of learning activities within a specific competence', null=True)),
                ('specific_competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_activities', to='syllabus.specificcompetence')),
            ],
            options={
                'verbose_name': 'Learning Activity',
                'verbose_name_plural': 'Learning Activities',
                'ordering': ['specific_competence', 'order'],
                'unique_together': {('specific_competence', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AnnualCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('institute', models.CharField(help_text="Jina la shule au chuo. Mfano: 'Shule ya Msingi Mzingi'", max_length=255, verbose_name='Taasis ya Shule/Chuo')),
                ('year', models.IntegerField(choices=[(2025, '2025'), (2026, '2026'), (2027, '2027')], default=2026, help_text='Chagua mwaka wa masomo (miaka mitatu tu: uliopita, huu, ujao).', verbose_name='Mwaka wa Masomo')),
                ('total_learning_days', models.PositiveIntegerField(help_text='Jumla ya siku za masomo kwa mwaka mzima.', verbose_name='Jumla ya Siku za Mafunzo')),
                ('term_start_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=20)),
                ('term_start_week', models.IntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4')], default=1)),
                ('term_start_date', models.DateField(default=datetime.date.today)),
                ('midterm_break_start_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='February', max_length=20)),
                ('midterm_break_start_week', models.IntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4')], default=1)),
                ('midterm_break_start_date', models.DateField(default=datetime.date.today)),
                ('midterm_start_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='February', max_length=20)),
                ('midterm_start_week', models.IntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4')], default=2)),
                ('midterm_start_date', models.DateField(default=datetime.date.today)),
                ('term_break_start_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='March', max_length=20)),
                ('term_break_start_week', models.IntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4')], default=1)),
                ('term_break_start_date', models.DateField(default=datetime.date.today)),
                ('annual_startmonth', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=20)),
                ('annual_startweek', models.IntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4')], default=1)),
                ('annual_startdate', models.DateField(default=datetime.date.today)),
                ('midannual_break_start_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='August', max_length=20)),
                ('midannual_break_start_week', models.IntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4')], default=1)),
                ('midannual_break_start_date', models.DateField(default=datetime.date.today)),
                ('midannual_start_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='July', max_length=20)),
                ('midannual_start_week', models.IntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4')], default=1)),
                ('midannual_start_date', models.DateField(default=datetime.date.today)),
                ('annual_break_start_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='December', max_length=20)),
                ('annual_break_start_week', models.IntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4')], default=1)),
                ('annual_break_start_date', models.DateField(default=datetime.date.today)),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Kalenda ya Mwaka',
                'verbose_name_plural': 'Kalenda za Mwaka',
                'ordering': ['year', 'institute'],
                'unique_together': {('year', 'institute')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='subjectversion',
            unique_together={('syllabus_version', 'subject', 'class_level')},
        ),
        migrations.CreateModel(
            name='SpecificLearningActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.TextField(help_text='Teaching method or approach')),
                ('leading', models.TextField(blank=True, help_text='Specific learning tasks or exercises', null=True)),
                ('name', models.TextField(help_text='Specific learning tasks or exercises')),
                ('assessment_criteria', models.TextField(help_text='Criteria for evaluating the activity')),
                ('teaching_aids', models.TextField(help_text='Teaching aids or materials used')),
                ('references', models.TextField(blank=True, help_text='References or sources', null=True)),
                ('periods', models.PositiveIntegerField(default=1, help_text='Number of periods allocated for this activity')),
                ('order', models.PositiveIntegerField(blank=True, editable=False, help_text='Order within the parent learning activity', null=True)),
                ('learning_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_activities', to='syllabus.learningactivity')),
            ],
            options={
                'verbose_name': 'Specific Learning Activity',
                'verbose_name_plural': 'Specific Learning Activities',
                'ordering': ['learning_activity', 'order'],
                'unique_together': {('learning_activity', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='maincompetence',
            unique_together={('subject_version', 'name')},
        ),
    ]
