# Generated by Django 4.2.16 on 2026-05-10 10:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificlearningactivity',
            name='leading',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Specific learning tasks or exercises (unaweza kuongeza nyingi)', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='specificlearningactivity',
            name='references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='References or sources (unaweza kuongeza nyingi)', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='specificlearningactivity',
            name='teaching_aids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Teaching aids or materials used (unaweza kuongeza nyingi)', null=True, size=None),
        ),
    ]
