# Generated by Django 4.2.16 on 2026-07-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_alter_specificlearningactivity_leading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificlearningactivity',
            name='exercise_questions',
            field=models.JSONField(blank=True, default=list, help_text="Practice exercise for this activity: a list of {'question': str, 'answer': str} objects, at least 3. 'answer' holds the worked solution for computational questions."),
        ),
        migrations.AddField(
            model_name='specificlearningactivity',
            name='lesson_notes',
            field=models.TextField(blank=True, default='', help_text='Nukuu za somo — the lesson content/notes a teacher references while teaching this activity'),
        ),
    ]
