# Generated by Django 4.2.16 on 2026-07-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_specificlearningactivity_exercise_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificlearningactivity',
            name='diagram_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('roman_numerals_chart', 'Roman numerals value chart'), ('unit_conversion_ladder', 'Unit conversion ladder (km/m/cm etc.)'), ('rectangle_diagram', 'Labelled rectangle/square (perimeter & area)'), ('fraction_bar', 'Fraction bar comparison'), ('clock_face', 'Clock face'), ('place_value_chart', 'Decimal place-value chart')], default='', help_text='Which illustrative diagram (drawn programmatically, no image upload needed) to show in the Nukuu za Somo document, if any.', max_length=32),
        ),
    ]
