# Generated by Django 4.2.16 on 2026-07-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0004_specificlearningactivity_diagram_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificlearningactivity',
            name='lesson_notes',
        ),
        migrations.AddField(
            model_name='specificlearningactivity',
            name='lesson_notes_details',
            field=models.TextField(blank=True, default='', help_text="Maelezo zaidi — brief breakdown of the topic's parts/types, only if it has several"),
        ),
        migrations.AddField(
            model_name='specificlearningactivity',
            name='lesson_notes_examples',
            field=models.TextField(blank=True, default='', help_text='Matumizi ya kila siku — real-life examples of where this concept is used'),
        ),
        migrations.AddField(
            model_name='specificlearningactivity',
            name='lesson_notes_intro',
            field=models.TextField(blank=True, default='', help_text='Utangulizi — explains the concept of the topic'),
        ),
    ]
