# Generated by Django 4.2.16 on 2026-07-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_remove_specificlearningactivity_lesson_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificlearningactivity',
            name='lesson_notes_examples',
        ),
        migrations.AddField(
            model_name='specificlearningactivity',
            name='lesson_notes_daily_life',
            field=models.TextField(blank=True, default='', help_text='Matumizi ya kila siku — real-life applications of this concept'),
        ),
        migrations.AddField(
            model_name='specificlearningactivity',
            name='lesson_notes_illustrations',
            field=models.TextField(blank=True, default='', help_text='Mifano — worked examples illustrating the concept itself'),
        ),
        migrations.AlterField(
            model_name='specificlearningactivity',
            name='lesson_notes_details',
            field=models.TextField(blank=True, default='', help_text='Maelezo zaidi — explains the concept in depth (types/parts, only if it has several)'),
        ),
        migrations.AlterField(
            model_name='specificlearningactivity',
            name='lesson_notes_intro',
            field=models.TextField(blank=True, default='', help_text='Utangulizi — the meaning and concept of the topic'),
        ),
    ]
