# Generated by Django 4.2.16 on 2026-07-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0006_remove_specificlearningactivity_lesson_notes_examples_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectversion',
            name='is_sekondari',
            field=models.BooleanField(default=False, help_text='Marks if this subject version is for Sekondari (secondary) curriculum. Neither is_awali nor is_sekondari set means Msingi (primary) — the default and, currently, only seeded curriculum family. Used to derive the school-type prefix (Shule ya Awali/Msingi/Sekondari) shown in generated documents, so teachers only register their bare school name.'),
        ),
        migrations.AlterField(
            model_name='subjectversion',
            name='is_awali',
            field=models.BooleanField(default=False, help_text='Marks if this subject version is for Awali (pre-primary) curriculum'),
        ),
    ]
