# Generated by Django 4.2.16 on 2026-07-24 10:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0007_subjectversion_is_sekondari_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=5000, help_text="Monthly fee in the wallet's currency (TZS).", max_digits=12)),
                ('is_active', models.BooleanField(default=False, help_text='True only while a paid, unexpired period is in effect.')),
                ('current_period_end', models.DateField(blank=True, help_text='Date the current paid period expires. Renewed automatically on/after this date if the wallet has sufficient balance.', null=True)),
                ('last_charge_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_charge_status', models.CharField(choices=[('never_charged', 'Never Charged'), ('success', 'Success'), ('failed', 'Failed (insufficient balance)')], default='never_charged', max_length=20)),
                ('last_failure_reason', models.TextField(blank=True, default='')),
                ('workstation', models.OneToOneField(help_text='The teacher work station this subscription grants full document access to.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='syllabus.teacherworkstation')),
            ],
            options={
                'verbose_name': 'Teacher Subscription',
                'verbose_name_plural': 'Teacher Subscriptions',
            },
        ),
    ]
