# Generated by Django 4.2.16 on 2026-07-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0008_teachersubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['workstation', 'day_of_week', 'period', '-created_at'], 'verbose_name': 'Ratiba ya Mwalimu', 'verbose_name_plural': 'Ratiba za Walimu'},
        ),
        migrations.AddField(
            model_name='timetable',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(1, 'Jumatatu'), (2, 'Jumanne'), (3, 'Jumatano'), (4, 'Alhamisi'), (5, 'Ijumaa'), (6, 'Jumamosi')], help_text='Chagua siku ambayo kipindi hiki kinafundishwa (Jumatatu-Jumamosi).', null=True, verbose_name='Siku ya Wiki'),
        ),
    ]
