# Generated by Django 4.2.16 on 2026-07-24 13:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0009_alter_timetable_options_timetable_day_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(default='Upimaji wa Nusu Muhula', max_length=255, verbose_name='Jina la Mtihani')),
                ('term', models.IntegerField(choices=[(1, 'Muhula wa Kwanza'), (2, 'Muhula wa Pili')], default=1, verbose_name='Muhula')),
                ('year', models.PositiveIntegerField(verbose_name='Mwaka')),
                ('max_score_per_subject', models.PositiveIntegerField(default=50, verbose_name='Alama za Juu kwa Somo')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='syllabus.classlevel', verbose_name='Darasa')),
                ('subjects', models.ManyToManyField(help_text='Masomo yanayohusika kwenye mtihani huu.', related_name='exams', to='syllabus.subject', verbose_name='Masomo')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='syllabus.teacherworkstation', verbose_name='Kituo cha Mwalimu')),
            ],
            options={
                'verbose_name': 'Mtihani',
                'verbose_name_plural': 'Mitihani',
                'ordering': ['-year', '-term'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('full_name', models.CharField(max_length=255, verbose_name='Jina la Mwanafunzi')),
                ('gender', models.CharField(choices=[('M', 'Mvulana'), ('F', 'Msichana')], max_length=1, verbose_name='Jinsia')),
                ('admission_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Namba ya Usajili')),
                ('is_active', models.BooleanField(default=True, verbose_name='Anaendelea na Masomo')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='syllabus.classlevel', verbose_name='Darasa')),
                ('workstation', models.ForeignKey(help_text='Shule/mwalimu aliyemsajili mwanafunzi huyu.', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='syllabus.teacherworkstation', verbose_name='Kituo cha Mwalimu')),
            ],
            options={
                'verbose_name': 'Mwanafunzi',
                'verbose_name_plural': 'Wanafunzi',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alama')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='syllabus.exam', verbose_name='Mtihani')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='syllabus.student', verbose_name='Mwanafunzi')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='syllabus.subject', verbose_name='Somo')),
            ],
            options={
                'verbose_name': 'Alama',
                'verbose_name_plural': 'Alama',
                'ordering': ['student', 'subject'],
                'unique_together': {('exam', 'student', 'subject')},
            },
        ),
    ]
