# Generated by Django 4.2.16 on 2026-08-19 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0010_exam_student_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamFormat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text="e.g. 'Std VII Maarifa ya Jamii Mock Format'", max_length=255)),
                ('paper_type', models.CharField(choices=[('quiz', 'Quiz'), ('test', 'Test'), ('examination', 'Examination')], max_length=20)),
                ('time_allowed_minutes', models.PositiveIntegerField(blank=True, help_text="Total time allowed, in minutes (e.g. 90 for 'Saa 1:30').", null=True)),
                ('instructions', models.TextField(blank=True, default='', help_text="Free-text 'Maelekezo'/'Instructions' block, one numbered rule per line.")),
                ('total_marks', models.PositiveIntegerField(default=0, editable=False, help_text="Sum of all sections' marks - kept in sync by recompute_total_marks().")),
                ('is_active', models.BooleanField(default=True)),
                ('class_level', models.ForeignKey(blank=True, help_text='Leave blank for a generic format reusable across class levels.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_formats', to='syllabus.classlevel')),
                ('subject', models.ForeignKey(blank=True, help_text='Leave blank for a generic format reusable across subjects.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_formats', to='syllabus.subject')),
            ],
            options={
                'verbose_name': 'Exam Format',
                'verbose_name_plural': 'Exam Formats',
                'ordering': ['paper_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamFormatSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text="e.g. 'SEHEMU A' / 'SECTION A'", max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('exam_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='syllabus.examformat')),
            ],
            options={
                'verbose_name': 'Exam Format Section',
                'verbose_name_plural': 'Exam Format Sections',
                'ordering': ['exam_format', 'order'],
                'unique_together': {('exam_format', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('term', models.PositiveIntegerField(blank=True, null=True)),
                ('seed', models.CharField(blank=True, default='', help_text='Random seed used, for reproducibility.', max_length=64)),
                ('exam_format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_papers', to='syllabus.examformat')),
                ('subject_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_papers', to='syllabus.subjectversion')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_papers', to='syllabus.teacherworkstation')),
            ],
            options={
                'verbose_name': 'Generated Paper',
                'verbose_name_plural': 'Generated Papers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField(help_text='The passage text itself.')),
                ('is_listening', models.BooleanField(default=False, help_text='True if this passage is meant to be read aloud by the invigilator (listening comprehension) rather than printed for the pupil to read.')),
                ('language', models.CharField(choices=[('sw', 'Swahili'), ('en', 'English')], default='sw', max_length=2)),
                ('learning_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='syllabus.learningactivity')),
            ],
            options={
                'verbose_name': 'Passage',
                'verbose_name_plural': 'Passages',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('matching', 'Matching'), ('fill_blank', 'Fill in the Blank'), ('short_answer', 'Short Answer'), ('calculation', 'Calculation'), ('sequencing', 'Sequencing'), ('map_diagram', 'Map/Diagram'), ('comprehension', 'Comprehension'), ('true_false', 'True/False')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('prompt', models.TextField(help_text='The question text itself.')),
                ('options', models.JSONField(blank=True, default=list, help_text="For mcq: list of choice strings. For matching: list of {'left': str, 'right': str} pairs.")),
                ('word_bank', models.JSONField(blank=True, default=list, help_text='For fill_blank questions offered from a word bank: list of candidate words/phrases.')),
                ('correct_answer', models.TextField(help_text='The correct answer/answer key. Required on every question.')),
                ('solution_steps', models.TextField(blank=True, default='', help_text='Full worked solution steps. Required for calculation-type questions.')),
                ('diagram_image', models.ImageField(blank=True, help_text='Map/diagram image this question refers to (map_diagram type).', null=True, upload_to='quiz_diagrams/')),
                ('marks', models.PositiveIntegerField(default=1, help_text="Default marks this question is worth when a format doesn't override it.")),
                ('source', models.CharField(blank=True, default='', help_text="Book/page citation this question is grounded in, e.g. 'TET(2023), HISABATI, KITABU CHA MWANAFUNZI, DARASA LA TATU'.", max_length=255)),
                ('language', models.CharField(choices=[('sw', 'Swahili'), ('en', 'English')], default='sw', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('learning_activity', models.ForeignKey(help_text='Topic this question belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='syllabus.learningactivity')),
                ('passage', models.ForeignKey(blank=True, help_text='Shared passage this question is based on (comprehension type).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='syllabus.passage')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['learning_activity', 'difficulty', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPaperQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('section_name', models.CharField(max_length=100)),
                ('order_in_section', models.PositiveIntegerField(default=1)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('generated_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='syllabus.generatedpaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_appearances', to='syllabus.question')),
            ],
            options={
                'verbose_name': 'Generated Paper Question',
                'verbose_name_plural': 'Generated Paper Questions',
                'ordering': ['generated_paper', 'section_name', 'order_in_section'],
            },
        ),
        migrations.CreateModel(
            name='ExamFormatSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('matching', 'Matching'), ('fill_blank', 'Fill in the Blank'), ('short_answer', 'Short Answer'), ('calculation', 'Calculation'), ('sequencing', 'Sequencing'), ('map_diagram', 'Map/Diagram'), ('comprehension', 'Comprehension'), ('true_false', 'True/False')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('count', models.PositiveIntegerField(default=1, help_text='How many questions of this type/difficulty to pick.')),
                ('marks_per_item', models.PositiveIntegerField(default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='syllabus.examformatsection')),
            ],
            options={
                'verbose_name': 'Exam Format Slot',
                'verbose_name_plural': 'Exam Format Slots',
                'ordering': ['section', 'order'],
            },
        ),
    ]
