# Generated by Django 4.2.16 on 2026-08-19 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0011_examformat_examformatsection_generatedpaper_passage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examformat',
            name='created_by_workstation',
            field=models.ForeignKey(blank=True, help_text='Set only for is_custom=True formats.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_exam_formats', to='syllabus.teacherworkstation'),
        ),
        migrations.AddField(
            model_name='examformat',
            name='is_custom',
            field=models.BooleanField(default=False, help_text="True if a teacher built this format ad-hoc for one generation (the 'manual' paper-builder flow), rather than an admin-curated library template. Custom formats are excluded from the browsable format list - they exist only so generation can reuse the normal ExamFormat/Section/Slot pipeline."),
        ),
    ]
