# Generated by Django 4.2.16 on 2026-08-20 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0012_examformat_created_by_workstation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Msimbo')),
                ('label_sw', models.CharField(max_length=100, verbose_name='Jina (Kiswahili)')),
                ('label_en', models.CharField(max_length=100, verbose_name='Jina (Kiingereza)')),
                ('is_fixed_routine', models.BooleanField(default=False, help_text='Mfano: kuwasili, usafi wa mazingira, mstarini na ukaguzi - hutokea kila siku bila kubadilika, hivyo huonyeshwa kama safu maalum kabla ya vipindi, si sehemu ya kizazi cha ratiba.', verbose_name='Ni Utaratibu wa Kila Siku')),
                ('is_whole_school', models.BooleanField(default=False, help_text='Mfano: michezo, klabu, dini - hutumika kwa madarasa yote kwa wakati mmoja.', verbose_name='Huathiri Shule Nzima')),
                ('default_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Aina ya Shughuli',
                'verbose_name_plural': 'Aina za Shughuli',
                'ordering': ['default_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MasterTimetableRoster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text='Mfano: Ratiba Kuu 2026', max_length=255, verbose_name='Jina')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Mwaka')),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_timetable_rosters', to='syllabus.teacherworkstation', verbose_name='Mmiliki')),
            ],
            options={
                'verbose_name': 'Ratiba Kuu - Roster',
                'verbose_name_plural': 'Ratiba Kuu - Rosters',
                'ordering': ['-year', '-created_at'],
                'unique_together': {('owner', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TimetablePeriodSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(help_text='Nafasi ya kipindi hiki siku nzima, kwa mpangilio (1, 2, 3, ...).', verbose_name='Mpangilio')),
                ('label', models.CharField(help_text="Mfano: '1', '2', au 'MAPUMZIKO' kwa mapumziko.", max_length=20, verbose_name='Jina la Kipindi')),
                ('timestart', models.TimeField(blank=True, null=True, verbose_name='Muda wa Kuanza')),
                ('timefinish', models.TimeField(blank=True, null=True, verbose_name='Muda wa Kumaliza')),
                ('is_break', models.BooleanField(default=False, help_text='Vipindi vya mapumziko havijumuishwi kwenye kizazi cha ratiba.', verbose_name='Ni Mapumziko')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_slots', to='syllabus.mastertimetableroster', verbose_name='Roster')),
            ],
            options={
                'verbose_name': 'Nafasi ya Kipindi',
                'verbose_name_plural': 'Nafasi za Vipindi',
                'ordering': ['roster', 'order'],
                'unique_together': {('roster', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TimetableTeacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('full_name', models.CharField(max_length=255, verbose_name='Jina Kamili')),
                ('initials', models.CharField(help_text="Herufi fupi zinazomtambulisha mwalimu kwenye ratiba, mfano 'DR'.", max_length=10, verbose_name='Herufi za Awali')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='syllabus.mastertimetableroster', verbose_name='Roster')),
                ('workstation', models.ForeignKey(blank=True, help_text='Ikiwa mwalimu huyu ana akaunti yake mwenyewe (hiari).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_timetable_entries', to='syllabus.teacherworkstation', verbose_name='Kituo cha Kazi')),
            ],
            options={
                'verbose_name': 'Mwalimu (Roster)',
                'verbose_name_plural': 'Walimu (Roster)',
                'ordering': ['roster', 'initials'],
                'unique_together': {('roster', 'initials')},
            },
        ),
        migrations.CreateModel(
            name='TimetableTeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('periods_per_week_override', models.PositiveSmallIntegerField(blank=True, help_text='Ikiachwa wazi, idadi ya vipindi kwa wiki itatumika kutoka kwenye muhtasari (Somo.periods_per_week).', null=True, verbose_name='Vipindi kwa Wiki (Badiliko)')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='syllabus.mastertimetableroster', verbose_name='Roster')),
                ('subject_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_timetable_assignments', to='syllabus.subjectversion', verbose_name='Somo (Darasa)')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='syllabus.timetableteacher', verbose_name='Mwalimu')),
            ],
            options={
                'verbose_name': 'Ugawaji wa Mwalimu',
                'verbose_name_plural': 'Ugawaji wa Walimu',
                'ordering': ['roster', 'teacher'],
                'unique_together': {('teacher', 'subject_version')},
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Jumatatu'), (2, 'Jumanne'), (3, 'Jumatano'), (4, 'Alhamisi'), (5, 'Ijumaa'), (6, 'Jumamosi')], verbose_name='Siku ya Wiki')),
                ('custom_label', models.CharField(blank=True, help_text='Tumia hii kwa shughuli isiyo kwenye orodha ya kawaida.', max_length=100, verbose_name='Jina Maalum')),
                ('source', models.CharField(choices=[('GENERATED', 'Kiotomatiki'), ('MANUAL', 'Kwa Mkono')], default='GENERATED', max_length=10, verbose_name='Chanzo')),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='syllabus.activitytype', verbose_name='Aina ya Shughuli')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='syllabus.timetableteacherassignment', verbose_name='Ugawaji')),
                ('class_level', models.ForeignKey(blank=True, help_text='Ikiachwa wazi, shughuli hii inahusu shule nzima (madarasa yote kwa wakati mmoja).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_timetable_slots', to='syllabus.classlevel', verbose_name='Darasa')),
                ('period_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='syllabus.timetableperiodslot', verbose_name='Nafasi ya Kipindi')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='syllabus.mastertimetableroster', verbose_name='Roster')),
            ],
            options={
                'verbose_name': 'Kiini cha Ratiba Kuu',
                'verbose_name_plural': 'Viini vya Ratiba Kuu',
                'ordering': ['roster', 'day_of_week', 'period_slot__order', 'class_level'],
            },
        ),
    ]
