# Generated by Django 4.2.16 on 2026-08-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0014_seed_activity_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherworkstation',
            name='free_downloads_used',
            field=models.PositiveIntegerField(default=0, help_text='Idadi ya nyaraka alizopakua bure kabla ya kuwa na usajili (angalia subscription_service.FREE_DOWNLOAD_LIMIT).'),
        ),
    ]
