# Generated by Django 4.2.16 on 2026-08-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0015_add_free_downloads_used'),
    ]

    operations = [
        # Integer -> JSONField has no implicit Postgres cast (AlterField's
        # generated ALTER COLUMN ... USING ...::jsonb fails outright). Fine
        # to just drop and recreate: this field was only added in the
        # previous migration, deployed minutes ago with zero real usage -
        # every row is still the default 0, nothing worth preserving.
        migrations.RemoveField(
            model_name='teacherworkstation',
            name='free_downloads_used',
        ),
        migrations.AddField(
            model_name='teacherworkstation',
            name='free_downloads_used',
            field=models.JSONField(blank=True, default=dict, help_text="Idadi ya nyaraka alizopakua bure kwa kila aina ya nyaraka (mfano {'SCHEME': 1, 'EXAM_RESULTS': 2}) - kila aina ina kikomo chake tofauti (angalia subscription_service.FREE_DOWNLOAD_LIMITS)."),
        ),
    ]
