# Generated by Django 4.2.16 on 2026-08-27 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syllabus', '0016_free_downloads_used_per_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherworkstation',
            name='free_downloads_used',
        ),
        migrations.CreateModel(
            name='TeacherDownloadCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_downloads_used', models.JSONField(blank=True, default=dict, help_text="Idadi ya nyaraka alizopakua bure kwa kila aina ya nyaraka (mfano {'SCHEME': 1, 'EXAM_RESULTS': 2}) - kila aina ina kikomo chake tofauti (angalia subscription_service.FREE_DOWNLOAD_LIMITS).")),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='download_credits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
