# Generated by Django 4.2.16 on 2026-07-12 12:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.UUIDField(help_text='id ya Institution au Business inayomiliki homepage hii')),
                ('name', models.CharField(help_text='Jina litakaloonekana kwenye homepage', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='homepage/logos/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_address', models.CharField(blank=True, max_length=255)),
                ('social_facebook', models.URLField(blank=True)),
                ('social_instagram', models.URLField(blank=True)),
                ('social_twitter', models.URLField(blank=True)),
                ('social_whatsapp', models.CharField(blank=True, max_length=30)),
                ('primary_color', models.CharField(default='#6d28d9', max_length=20)),
                ('secondary_color', models.CharField(default='#1f2937', max_length=20)),
                ('is_published', models.BooleanField(default=True, help_text='Ukizima, homepage haionekani tena kwa umma (bado unaweza kuihariri)')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
            },
        ),
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='Tunachofanya', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/whatwedo/')),
                ('cta_text', models.CharField(blank=True, default='Jifunze Zaidi', max_length=50)),
                ('cta_link', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_we_do_sections', to='homepage.homepage')),
            ],
            options={
                'verbose_name': 'What We Do Section',
                'verbose_name_plural': 'What We Do Sections',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatWeDoService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('icon', models.CharField(blank=True, help_text='Jina la icon, mfano: truck, heart', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('what_we_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='homepage.whatwedo')),
            ],
            options={
                'verbose_name': 'What We Do Service',
                'verbose_name_plural': 'What We Do Services',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WhatWeDoImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='homepage/whatwedo/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('what_we_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_images', to='homepage.whatwedo')),
            ],
            options={
                'verbose_name': 'What We Do Image',
                'verbose_name_plural': 'What We Do Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_name', models.CharField(max_length=150)),
                ('client_role', models.CharField(blank=True, max_length=150)),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='homepage/testimonials/')),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='homepage.homepage')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='homepage/hero/')),
                ('cta_text', models.CharField(blank=True, default='Wasiliana Nasi', max_length=50)),
                ('cta_link', models.CharField(blank=True, default='#contact', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_sections', to='homepage.homepage')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='homepage.homepage')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='Kuhusu Sisi', max_length=200)),
                ('description', models.TextField()),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/about/')),
                ('stats', models.JSONField(blank=True, default=list, help_text="Orodha ya {number, label}, mfano [{'number': '500+', 'label': 'Wateja'}]")),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_sections', to='homepage.homepage')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='homepage/about/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='homepage.aboutsection')),
            ],
            options={
                'verbose_name': 'About Image',
                'verbose_name_plural': 'About Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='homepage',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_homepage_per_owner'),
        ),
    ]
