# Generated by Django 4.2.16 on 2026-05-10 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gov_integration.models.verification_request


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiini', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('TZ', 'Tanzania'), ('KE', 'Kenya'), ('UG', 'Uganda'), ('RW', 'Rwanda'), ('BI', 'Burundi'), ('SS', 'South Sudan')], max_length=2)),
                ('base_url', models.URLField()),
                ('auth_type', models.CharField(default='JWT', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('TZ', 'Tanzania'), ('KE', 'Kenya'), ('UG', 'Uganda'), ('RW', 'Rwanda'), ('BI', 'Burundi'), ('SS', 'South Sudan')], max_length=2, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('integration_ready', models.BooleanField(default=False)),
                ('default_language', models.CharField(default='en', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_types', to='gov_integration.countryconfig')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiini.institution')),
                ('service', models.ForeignKey(blank=True, default=gov_integration.models.verification_request.get_default_service_pk, help_text="Service inayohusiana na ombi la uthibitishaji, default ni 'Freelancer Service'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='gov_integration.servicetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('raw_response', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gov_integration.verificationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=512)),
                ('refresh_token', models.CharField(blank=True, max_length=512)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gov_integration.apiendpoint')),
            ],
        ),
        migrations.CreateModel(
            name='CountryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_mou', models.BooleanField(default=False)),
                ('requires_license', models.BooleanField(default=False)),
                ('local_partner_required', models.BooleanField(default=False)),
                ('api_access_mode', models.CharField(default='private', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='gov_integration.countryconfig')),
            ],
        ),
    ]
