# Generated by Django 4.2.16 on 2026-07-12 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_product_tags_productcategory_product_category'),
        ('gov_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Biashara husika, ikiwa ombi hili ni la uthibitisho wa biashara (mf. leseni).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to='businesses.business'),
        ),
    ]
