# Generated by Django 4.2.16 on 2026-05-10 07:14

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('details', models.TextField(blank=True)),
                ('retries', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.FloatField(blank=True, help_text='Execution duration in milliseconds', null=True)),
                ('worker_id', models.CharField(blank=True, help_text='Celery worker hostname', max_length=100, null=True)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, help_text='External reference e.g. transaction ref', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Task Log',
                'verbose_name_plural': 'Task Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeadLetterQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('FAILED', 'Failed'), ('RETRY_EXHAUSTED', 'Retry exhausted'), ('MANUAL_PAUSED', 'Manual paused')], default='FAILED', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('requeued', models.BooleanField(default=False)),
                ('requeued_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jamiitasks_deadletterqueue',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_name'], name='jamiitasks__task_na_a5f999_idx'), models.Index(fields=['task_id'], name='jamiitasks__task_id_198402_idx'), models.Index(fields=['status'], name='jamiitasks__status_47b041_idx')],
            },
        ),
    ]
