# Generated by Django 4.2.16 on 2026-07-17 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0005_alter_auditlog_action'),
        ('jamiiwallet', '0012_escrowhold'),
        ('gov_integration', '0002_verificationrequest_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('AIRTIME', 'Airtime'), ('TV', 'TV Subscription'), ('WATER', 'Water')], max_length=20)),
                ('config_key', models.CharField(help_text="Jina la config kwenye billpay_api_config.py, mf. 'TZ_LUKU'.", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billers', to='gov_integration.countryconfig')),
            ],
            options={
                'verbose_name': 'Biller',
                'verbose_name_plural': 'Billers',
                'ordering': ['country', 'category', 'name'],
                'unique_together': {('country', 'config_key')},
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_number', models.CharField(help_text='Namba ya mita/simu/decoder inayolipiwa.', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('_token_or_receipt', models.TextField(blank=True, db_column='token_or_receipt', null=True)),
                ('biller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billpay.biller')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_payments', to='payments.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_payments', to=settings.AUTH_USER_MODEL)),
                ('wallet_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_payment', to='jamiiwallet.transaction')),
            ],
            options={
                'verbose_name': 'Bill Payment',
                'verbose_name_plural': 'Bill Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='billpay_bil_user_id_259d2c_idx')],
            },
        ),
    ]
